name: offline17000ft
description: "A new Flutter project."

publish_to: 'none'

version: 4.0.0

environment:
  sdk: '>=3.5.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  win32: ^5.5.4
  image: ^4.2.0
  flutter_image_compress: ^2.3.0
  package_info_plus: ^8.0.0
  google_fonts: ^6.2.1
  path_provider: ^2.0.11
  permission_handler: ^10.4.0
  json_annotation: ^4.8.0
  connectivity_plus: ^5.0.2
  device_info_plus: ^10.4.0
#  file_picker: ^8.1.5
  open_file: ^3.2.1
  pdfx: ^2.8.0
  intl: ^0.19.0
  image_picker: ^1.1.1
  get: ^4.6.6
  http: ^1.1.0
  http_parser: ^4.0.0
  get_storage: ^2.1.1
  awesome_dialog: ^3.2.0
  persistent_bottom_nav_bar: ^5.0.2
  syncfusion_flutter_pdfviewer: ^27.2.3
  flutter_local_notifications: ^17.0.1
  shared_preferences: ^2.2.3
  font_awesome_flutter: ^10.7.0
  sqflite: ^2.3.3+1
  path: ^1.9.0
  dropdown_search: ^5.0.6
  hive: ^2.0.0
  hive_flutter: ^1.1.0
  logger: ^2.5.0


  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.14.2
  fl_chart: ^0.63.0

dependency_overrides:
  device_info_plus: ^9.1.2


flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo_17000ft.png" # Ensure this file exists at the specified path
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/logo.png" # Ensure this file exists

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/offline17000ft.db # Make sure this file exists and is correctly named
